Repository openrewrite/rewrite-logging-frameworks, pull requests merged in 2023-11, with the labels that each got.

#117 Use non-identical display names for system print recipes (#116)
  src/main/java/org/openrewrite/java/logging/SystemErrToLogging.java
  src/main/java/org/openrewrite/java/logging/SystemOutToLogging.java
Labels: documentation

#118 do not modify when not Object::toString()
  src/main/java/org/openrewrite/java/logging/slf4j/Slf4jLogShouldBeConstant.java
  src/test/java/org/openrewrite/java/logging/slf4j/Slf4jLogShouldBeConstantTest.java
Labels: bug

#119 Migrate from Apache Commons Logging to SLF4J
  build.gradle.kts
  src/main/java/org/openrewrite/java/logging/LoggingFramework.java
  src/main/java/org/openrewrite/java/logging/PrintStackTraceToLogError.java
  src/main/java/org/openrewrite/java/logging/SystemErrToLogging.java
  src/main/java/org/openrewrite/java/logging/SystemOutToLogging.java
  src/main/java/org/openrewrite/java/logging/SystemPrintToLogging.java
  src/main/resources/META-INF/rewrite/slf4j.yml
  src/test/java/org/openrewrite/java/logging/slf4j/CommonsLoggingToSlf4j1Test.java
Labels: recipe

#120 Escape dollar sign on messages
  src/main/java/org/openrewrite/java/logging/ParameterizedLogging.java
  src/test/java/org/openrewrite/java/logging/ParameterizedLoggingTest.java
Labels: bug

#121 Replace Lombok logging annotations when switching frameworks
  src/main/java/org/openrewrite/java/logging/ChangeLombokLogAnnotation.java
  src/main/resources/META-INF/rewrite/log4j.yml
  src/main/resources/META-INF/rewrite/slf4j.yml
  src/test/java/org/openrewrite/java/logging/slf4j/CommonsLoggingToSlf4j1Test.java
  src/test/java/org/openrewrite/java/logging/slf4j/Log4j2ToSlf4j1Test.java
Labels: recipe

#122 Minor cleanup following #121
  src/main/java/org/openrewrite/java/logging/LoggingFramework.java
  src/main/java/org/openrewrite/java/logging/PrintStackTraceToLogError.java
  src/main/java/org/openrewrite/java/logging/SystemErrToLogging.java
  src/main/java/org/openrewrite/java/logging/SystemOutToLogging.java
  src/main/java/org/openrewrite/java/logging/SystemPrintToLogging.java
  src/main/java/org/openrewrite/java/logging/log4j/PrependRandomName.java
  src/main/java/org/openrewrite/java/logging/logback/Log4jAppenderToLogback.java
  src/main/java/org/openrewrite/java/logging/slf4j/Slf4jLogShouldBeConstant.java
Labels: enhancement

#126 Fix concurrent modification exception when using JUL
  src/main/java/org/openrewrite/java/logging/SystemErrToLogging.java
  src/main/java/org/openrewrite/java/logging/SystemOutToLogging.java
  src/test/java/org/openrewrite/java/logging/SystemOutToLoggingTest.java
Labels: bug
